---
abstract: 'Compile .cgi scripts to a code reference like ModPerl::Registry'
author:
  - 'Tatsuhiko Miyagawa <miyagawa@bulknews.net>'
build_requires:
  Test::More: '0'
  Test::NoWarnings: '0'
  Test::Requires: '0'
configure_requires:
  Module::Build::Tiny: '0.039'
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.8, Dist::Zilla version 5.021, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: CGI-Compile
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  File::pushd: '0'
  perl: '5.008001'
resources:
  bugtracker: https://github.com/miyagawa/CGI-Compile/issues
  homepage: https://github.com/miyagawa/CGI-Compile
  repository: https://github.com/miyagawa/CGI-Compile.git
version: '0.18'
x_contributors:
  - 'Hans Dieter Pearcey <hdp@cpan.org>'
  - 'Rafael Kitover <rkitover@cpan.org>'
  - 'Torsten Förtsch <torsten@binary.com>'
  - 'kocoureasy <igor.bujna@post.cz>'
  - 'lestrrat <lestrrat+github@gmail.com>'
